
name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build APK
        run: |
          chmod +x gradlew || true
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Daily_Tasks_Manager_APK
          path: app/build/outputs/apk/debug/*.apk
